apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: dev

images:
- name: testeaction
  newName: labacl/dev
  newTag: testeaction.8b82d8d
